#!/bin/bash
xmodmap -e "remove control = Control_L Control_R"
xmodmap -e "remove mod4 = Super_L Super_R"
xmodmap -e "add control = Super_L Super_R"

echo "control key succesfully mapped to command key"

